### ISSUE TITLE
Wire up login to new db stuff

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#17]
I've tried to show, as much as possible, what methods can be used in place of previous methods from UserList.java and User.java.

**Comment by elfiesmelfie** [comment]
Can we log in using the username/password combos from the assignment brief?

**Comment by Lexoph** [comment]
The front end is done. You modified the Security class and I am assuming that it will work. Currently, we are not able to check this yet because we can't access the database.

**Comment by elfiesmelfie** [comment]
I thought you had access to the database?
Dara, can you do this?

**Comment by daradermody** [comment]
I can access the database manually in NetBeans, but not using the actual Java code (due to that error we saw yesterday). Further investigation seemed to point towards the database; apparently the way you set it up (in Other Schema) may have been incorrect. I set up the database again and pushed. However there may be some discrepancies in the attributes of the first column. Also, the data will have to be pushed to the database again.

The database seems to work for me (i.e. it will compile and deploy), but I have yet to test accessing it.

**Comment by elfiesmelfie** [comment]
I followed the instructions from the lab sheet. The entities are linked to that particular database though, so they may actually need to be modified :-(
The commands for creating the database are listed in a text file in the DistSysProj3 folder.
I've pulled already, and that may have overwritten the data. :-(

**Comment by elfiesmelfie** [comment]
My DB wasn't in other schema

**Comment by elfiesmelfie** [comment]
So, what changes do I need to make to use the DB? Is the data preserved?

**Comment by daradermody** [comment]
I did some work and figured something out (I guess). The whole database setup is a bit difficult when it comes to transferring between computers. But doing the following should work:

Create a new database called 10105239 with the username and password of "emma" as it was before. _Recreate_ the tables (instead of the option below _create table_) and use each of the following scripts: https://drive.google.com/folderview?id=0B9NVhaEF2zR6bFozN19pVDREbTg&usp=sharing

Then change the persistance.xml so that it refers to _10105239_.

Note though, that this configuration doesn't auto-generate an ID column, so it might have to be created again or fiddled with, but I ain't know how do that. :(

**Comment by elfiesmelfie** [comment]
Two options for the id column... either fiddle with the table,  or generate the id when the product/comnent/user is created (in java)...

Regards, 
Emma

Sent from Samsung Mobile

-------- Original message --------
